Traceback (most recent call last):
  File "check_homework.py", line 65
  File "PyLuaTblParser.py", line 161
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 557
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 605
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 599
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 569
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 573
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 577
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 575
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 561
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 497
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 621
  File "PyLuaTblParser.py", line 473
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 479
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 481
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 483
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 485
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 625
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 465
  File "PyLuaTblParser.py", line 465
  File "PyLuaTblParser.py", line 557
  File "PyLuaTblParser.py", line 557
  File "PyLuaTblParser.py", line 557
  File "PyLuaTblParser.py", line 561
  File "PyLuaTblParser.py", line 557
  File "PyLuaTblParser.py", line 561
  File "PyLuaTblParser.py", line 557
  File "PyLuaTblParser.py", line 561
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 543
  File "PyLuaTblParser.py", line 577
  File "PyLuaTblParser.py", line 605
  File "PyLuaTblParser.py", line 607
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 593
  File "PyLuaTblParser.py", line 609
  File "PyLuaTblParser.py", line 591
  File "PyLuaTblParser.py", line 607
  File "PyLuaTblParser.py", line 585
  File "PyLuaTblParser.py", line 465
  File "PyLuaTblParser.py", line 591
  File "PyLuaTblParser.py", line 585
  File "PyLuaTblParser.py", line 595
  File "PyLuaTblParser.py", line 577
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 573
  File "PyLuaTblParser.py", line 597
  File "PyLuaTblParser.py", line 593
  File "PyLuaTblParser.py", line 593
  File "PyLuaTblParser.py", line 577
  File "PyLuaTblParser.py", line 595
  File "PyLuaTblParser.py", line 607
  File "PyLuaTblParser.py", line 605
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 573
  File "PyLuaTblParser.py", line 597
  File "PyLuaTblParser.py", line 593
  File "PyLuaTblParser.py", line 599
  File "PyLuaTblParser.py", line 569
  File "PyLuaTblParser.py", line 573
  File "PyLuaTblParser.py", line 607
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 497
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 621
  File "PyLuaTblParser.py", line 473
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 479
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 481
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 483
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 485
  File "PyLuaTblParser.py", line 625
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 465
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 465
  File "PyLuaTblParser.py", line 557
  File "PyLuaTblParser.py", line 591
  File "PyLuaTblParser.py", line 609
  File "PyLuaTblParser.py", line 569
  File "PyLuaTblParser.py", line 607
  File "PyLuaTblParser.py", line 577
  File "PyLuaTblParser.py", line 615
  File "PyLuaTblParser.py", line 607
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 497
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 621
  File "PyLuaTblParser.py", line 559
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 597
  File "PyLuaTblParser.py", line 571
  File "PyLuaTblParser.py", line 587
  File "PyLuaTblParser.py", line 577
  File "PyLuaTblParser.py", line 573
  File "PyLuaTblParser.py", line 607
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 613
  File "PyLuaTblParser.py", line 585
  File "PyLuaTblParser.py", line 607
  File "PyLuaTblParser.py", line 583
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 473
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 593
  File "PyLuaTblParser.py", line 577
  File "PyLuaTblParser.py", line 593
  File "PyLuaTblParser.py", line 571
  File "PyLuaTblParser.py", line 577
  File "PyLuaTblParser.py", line 603
  File "PyLuaTblParser.py", line 559
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 497
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 621
  File "PyLuaTblParser.py", line 559
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 569
  File "PyLuaTblParser.py", line 603
  File "PyLuaTblParser.py", line 603
  File "PyLuaTblParser.py", line 569
  File "PyLuaTblParser.py", line 617
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 613
  File "PyLuaTblParser.py", line 585
  File "PyLuaTblParser.py", line 607
  File "PyLuaTblParser.py", line 583
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 473
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 577
  File "PyLuaTblParser.py", line 591
  File "PyLuaTblParser.py", line 577
  File "PyLuaTblParser.py", line 593
  File "PyLuaTblParser.py", line 577
  File "PyLuaTblParser.py", line 595
  File "PyLuaTblParser.py", line 607
  File "PyLuaTblParser.py", line 559
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 625
  File "PyLuaTblParser.py", line 625
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 601
  File "PyLuaTblParser.py", line 609
  File "PyLuaTblParser.py", line 597
  File "PyLuaTblParser.py", line 607
  File "PyLuaTblParser.py", line 577
  File "PyLuaTblParser.py", line 605
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 497
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 451
  File "PyLuaTblParser.py", line 445
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 479
  File "PyLuaTblParser.py", line 493
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 455
  File "PyLuaTblParser.py", line 471
  File "PyLuaTblParser.py", line 615
  File "PyLuaTblParser.py", line 471
  File "PyLuaTblParser.py", line 471
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 457
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 449
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 471
  File "PyLuaTblParser.py", line 615
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 471
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 479
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 451
  File "PyLuaTblParser.py", line 445
  File "PyLuaTblParser.py", line 615
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 493
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 557
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 559
  File "PyLuaTblParser.py", line 559
  File "PyLuaTblParser.py", line 559
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 559
  File "PyLuaTblParser.py", line 571
  File "PyLuaTblParser.py", line 559
  File "PyLuaTblParser.py", line 579
  File "PyLuaTblParser.py", line 559
  File "PyLuaTblParser.py", line 595
  File "PyLuaTblParser.py", line 559
  File "PyLuaTblParser.py", line 603
  File "PyLuaTblParser.py", line 559
  File "PyLuaTblParser.py", line 607
  File "PyLuaTblParser.py", line 567
  File "PyLuaTblParser.py", line 473
  File "PyLuaTblParser.py", line 627
  File "PyLuaTblParser.py", line 441
  File "PyLuaTblParser.py", line 503
  File "PyLuaTblParser.py", line 445
  File "PyLuaTblParser.py", line 447
  File "PyLuaTblParser.py", line 449
  File "PyLuaTblParser.py", line 563
  File "PyLuaTblParser.py", line 451
  File "PyLuaTblParser.py", line 459
  File "PyLuaTblParser.py", line 455
  File "PyLuaTblParser.py", line 457
  File "PyLuaTblParser.py", line 565
  File "PyLuaTblParser.py", line 461
  File "PyLuaTblParser.py", line 465
  File "PyLuaTblParser.py", line 497
  File "PyLuaTblParser.py", line 557
  File "PyLuaTblParser.py", line 561
  File "PyLuaTblParser.py", line 621
  File "PyLuaTblParser.py", line 625
  File "PyLuaTblParser.py", line 623
  File "PyLuaTblParser.py", line 493
  File "PyLuaTblParser.py", line 491
  File "PyLuaTblParser.py", line 453
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 467
  File "PyLuaTblParser.py", line 469
  File "PyLuaTblParser.py", line 495
  File "PyLuaTblParser.py", line 499
  File "PyLuaTblParser.py", line 501
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 561
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 497
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 505
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 589
  File "PyLuaTblParser.py", line 577
  File "PyLuaTblParser.py", line 617
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 573
  File "PyLuaTblParser.py", line 569
  File "PyLuaTblParser.py", line 595
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 571
  File "PyLuaTblParser.py", line 577
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 569
  File "PyLuaTblParser.py", line 595
  File "PyLuaTblParser.py", line 617
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 605
  File "PyLuaTblParser.py", line 607
  File "PyLuaTblParser.py", line 603
  File "PyLuaTblParser.py", line 585
  File "PyLuaTblParser.py", line 595
  File "PyLuaTblParser.py", line 581
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 561
  File "PyLuaTblParser.py", line 561
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 465
  File "PyLuaTblParser.py", line 465
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 561
  File "PyLuaTblParser.py", line 561
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 573
  File "PyLuaTblParser.py", line 597
  File "PyLuaTblParser.py", line 593
  File "PyLuaTblParser.py", line 599
  File "PyLuaTblParser.py", line 569
  File "PyLuaTblParser.py", line 573
  File "PyLuaTblParser.py", line 607
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 497
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 621
  File "PyLuaTblParser.py", line 473
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 479
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 481
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 483
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 485
  File "PyLuaTblParser.py", line 625
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 591
  File "PyLuaTblParser.py", line 609
  File "PyLuaTblParser.py", line 569
  File "PyLuaTblParser.py", line 607
  File "PyLuaTblParser.py", line 577
  File "PyLuaTblParser.py", line 615
  File "PyLuaTblParser.py", line 607
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 497
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 621
  File "PyLuaTblParser.py", line 559
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 597
  File "PyLuaTblParser.py", line 571
  File "PyLuaTblParser.py", line 587
  File "PyLuaTblParser.py", line 577
  File "PyLuaTblParser.py", line 573
  File "PyLuaTblParser.py", line 607
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 613
  File "PyLuaTblParser.py", line 585
  File "PyLuaTblParser.py", line 607
  File "PyLuaTblParser.py", line 583
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 473
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 593
  File "PyLuaTblParser.py", line 577
  File "PyLuaTblParser.py", line 593
  File "PyLuaTblParser.py", line 571
  File "PyLuaTblParser.py", line 577
  File "PyLuaTblParser.py", line 603
  File "PyLuaTblParser.py", line 559
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 497
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 621
  File "PyLuaTblParser.py", line 559
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 569
  File "PyLuaTblParser.py", line 603
  File "PyLuaTblParser.py", line 603
  File "PyLuaTblParser.py", line 569
  File "PyLuaTblParser.py", line 617
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 613
  File "PyLuaTblParser.py", line 585
  File "PyLuaTblParser.py", line 607
  File "PyLuaTblParser.py", line 583
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 473
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 577
  File "PyLuaTblParser.py", line 591
  File "PyLuaTblParser.py", line 577
  File "PyLuaTblParser.py", line 593
  File "PyLuaTblParser.py", line 577
  File "PyLuaTblParser.py", line 595
  File "PyLuaTblParser.py", line 607
  File "PyLuaTblParser.py", line 559
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 625
  File "PyLuaTblParser.py", line 625
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 601
  File "PyLuaTblParser.py", line 609
  File "PyLuaTblParser.py", line 597
  File "PyLuaTblParser.py", line 607
  File "PyLuaTblParser.py", line 577
  File "PyLuaTblParser.py", line 605
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 497
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 451
  File "PyLuaTblParser.py", line 445
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 479
  File "PyLuaTblParser.py", line 493
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 455
  File "PyLuaTblParser.py", line 471
  File "PyLuaTblParser.py", line 615
  File "PyLuaTblParser.py", line 471
  File "PyLuaTblParser.py", line 471
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 457
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 449
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 471
  File "PyLuaTblParser.py", line 615
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 471
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 479
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 451
  File "PyLuaTblParser.py", line 445
  File "PyLuaTblParser.py", line 615
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 493
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 557
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 559
  File "PyLuaTblParser.py", line 559
  File "PyLuaTblParser.py", line 559
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 559
  File "PyLuaTblParser.py", line 571
  File "PyLuaTblParser.py", line 559
  File "PyLuaTblParser.py", line 579
  File "PyLuaTblParser.py", line 559
  File "PyLuaTblParser.py", line 595
  File "PyLuaTblParser.py", line 559
  File "PyLuaTblParser.py", line 603
  File "PyLuaTblParser.py", line 559
  File "PyLuaTblParser.py", line 607
  File "PyLuaTblParser.py", line 567
  File "PyLuaTblParser.py", line 473
  File "PyLuaTblParser.py", line 627
  File "PyLuaTblParser.py", line 441
  File "PyLuaTblParser.py", line 503
  File "PyLuaTblParser.py", line 445
  File "PyLuaTblParser.py", line 447
  File "PyLuaTblParser.py", line 449
  File "PyLuaTblParser.py", line 563
  File "PyLuaTblParser.py", line 451
  File "PyLuaTblParser.py", line 459
  File "PyLuaTblParser.py", line 455
  File "PyLuaTblParser.py", line 457
  File "PyLuaTblParser.py", line 565
  File "PyLuaTblParser.py", line 461
  File "PyLuaTblParser.py", line 465
  File "PyLuaTblParser.py", line 497
  File "PyLuaTblParser.py", line 557
  File "PyLuaTblParser.py", line 561
  File "PyLuaTblParser.py", line 621
  File "PyLuaTblParser.py", line 625
  File "PyLuaTblParser.py", line 623
  File "PyLuaTblParser.py", line 493
  File "PyLuaTblParser.py", line 491
  File "PyLuaTblParser.py", line 453
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 467
  File "PyLuaTblParser.py", line 469
  File "PyLuaTblParser.py", line 495
  File "PyLuaTblParser.py", line 499
  File "PyLuaTblParser.py", line 501
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 561
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 497
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 505
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 589
  File "PyLuaTblParser.py", line 577
  File "PyLuaTblParser.py", line 617
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 573
  File "PyLuaTblParser.py", line 569
  File "PyLuaTblParser.py", line 595
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 571
  File "PyLuaTblParser.py", line 577
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 569
  File "PyLuaTblParser.py", line 595
  File "PyLuaTblParser.py", line 617
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 605
  File "PyLuaTblParser.py", line 607
  File "PyLuaTblParser.py", line 603
  File "PyLuaTblParser.py", line 585
  File "PyLuaTblParser.py", line 595
  File "PyLuaTblParser.py", line 581
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 625
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 471
  File "PyLuaTblParser.py", line 467
  File "PyLuaTblParser.py", line 481
  File "PyLuaTblParser.py", line 439
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 473
  File "PyLuaTblParser.py", line 479
  File "PyLuaTblParser.py", line 473
  File "PyLuaTblParser.py", line 481
  File "PyLuaTblParser.py", line 489
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 483
  File "PyLuaTblParser.py", line 481
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 481
  File "PyLuaTblParser.py", line 487
  File "PyLuaTblParser.py", line 489
  File "PyLuaTblParser.py", line 485
  File "PyLuaTblParser.py", line 489
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 487
  File "PyLuaTblParser.py", line 479
  File "PyLuaTblParser.py", line 483
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 483
  File "PyLuaTblParser.py", line 479
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 487
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 485
  File "PyLuaTblParser.py", line 489
  File "PyLuaTblParser.py", line 481
  File "PyLuaTblParser.py", line 471
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 487
  File "PyLuaTblParser.py", line 487
  File "PyLuaTblParser.py", line 479
  File "PyLuaTblParser.py", line 473
  File "PyLuaTblParser.py", line 489
  File "PyLuaTblParser.py", line 485
  File "PyLuaTblParser.py", line 473
  File "PyLuaTblParser.py", line 483
  File "PyLuaTblParser.py", line 489
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 489
  File "PyLuaTblParser.py", line 489
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 485
  File "PyLuaTblParser.py", line 481
  File "PyLuaTblParser.py", line 473
  File "PyLuaTblParser.py", line 471
  File "PyLuaTblParser.py", line 481
  File "PyLuaTblParser.py", line 487
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 471
  File "PyLuaTblParser.py", line 489
  File "PyLuaTblParser.py", line 485
  File "PyLuaTblParser.py", line 479
  File "PyLuaTblParser.py", line 489
  File "PyLuaTblParser.py", line 479
  File "PyLuaTblParser.py", line 479
  File "PyLuaTblParser.py", line 481
  File "PyLuaTblParser.py", line 489
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 467
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 467
  File "PyLuaTblParser.py", line 473
  File "PyLuaTblParser.py", line 479
  File "PyLuaTblParser.py", line 473
  File "PyLuaTblParser.py", line 481
  File "PyLuaTblParser.py", line 489
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 483
  File "PyLuaTblParser.py", line 481
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 481
  File "PyLuaTblParser.py", line 487
  File "PyLuaTblParser.py", line 489
  File "PyLuaTblParser.py", line 485
  File "PyLuaTblParser.py", line 489
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 487
  File "PyLuaTblParser.py", line 479
  File "PyLuaTblParser.py", line 483
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 483
  File "PyLuaTblParser.py", line 479
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 487
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 485
  File "PyLuaTblParser.py", line 489
  File "PyLuaTblParser.py", line 481
  File "PyLuaTblParser.py", line 471
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 487
  File "PyLuaTblParser.py", line 487
  File "PyLuaTblParser.py", line 479
  File "PyLuaTblParser.py", line 473
  File "PyLuaTblParser.py", line 489
  File "PyLuaTblParser.py", line 485
  File "PyLuaTblParser.py", line 473
  File "PyLuaTblParser.py", line 483
  File "PyLuaTblParser.py", line 489
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 489
  File "PyLuaTblParser.py", line 489
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 485
  File "PyLuaTblParser.py", line 481
  File "PyLuaTblParser.py", line 473
  File "PyLuaTblParser.py", line 471
  File "PyLuaTblParser.py", line 481
  File "PyLuaTblParser.py", line 487
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 471
  File "PyLuaTblParser.py", line 489
  File "PyLuaTblParser.py", line 485
  File "PyLuaTblParser.py", line 479
  File "PyLuaTblParser.py", line 489
  File "PyLuaTblParser.py", line 479
  File "PyLuaTblParser.py", line 479
  File "PyLuaTblParser.py", line 481
  File "PyLuaTblParser.py", line 489
  File "PyLuaTblParser.py", line 475
  File "PyLuaTblParser.py", line 477
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 473
  File "PyLuaTblParser.py", line 471
  File "PyLuaTblParser.py", line 483
  File "PyLuaTblParser.py", line 483
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 393
  File "PyLuaTblParser.py", line 463
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 603
  File "PyLuaTblParser.py", line 597
  File "PyLuaTblParser.py", line 605
  File "PyLuaTblParser.py", line 577
  File "PyLuaTblParser.py", line 571
  File "PyLuaTblParser.py", line 609
  File "PyLuaTblParser.py", line 575
  File "PyLuaTblParser.py", line 443
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 401
  File "PyLuaTblParser.py", line 395
  File "PyLuaTblParser.py", line 625
  File "PyLuaTblParser.py", line 625
  File "PyLuaTblParser.py", line 373
