Traceback (most recent call last):
  File "check_homework.py", line 65
  File "PyLuaTblParser.py", line 50
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 548
  File "PyLuaTblParser.py", line 548
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 494
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 486
  File "PyLuaTblParser.py", line 520
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 546
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 492
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 536
  File "PyLuaTblParser.py", line 546
  File "PyLuaTblParser.py", line 532
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 416
  File "PyLuaTblParser.py", line 416
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 548
  File "PyLuaTblParser.py", line 522
  File "PyLuaTblParser.py", line 538
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 524
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 564
  File "PyLuaTblParser.py", line 536
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 534
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 424
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 544
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 544
  File "PyLuaTblParser.py", line 522
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 520
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 520
  File "PyLuaTblParser.py", line 568
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 564
  File "PyLuaTblParser.py", line 536
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 534
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 424
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 544
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 546
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 508
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 548
  File "PyLuaTblParser.py", line 522
  File "PyLuaTblParser.py", line 538
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 524
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 564
  File "PyLuaTblParser.py", line 536
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 534
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 424
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 544
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 544
  File "PyLuaTblParser.py", line 522
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 512
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 520
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 520
  File "PyLuaTblParser.py", line 568
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 564
  File "PyLuaTblParser.py", line 536
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 534
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 424
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 544
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 546
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 508
  File "PyLuaTblParser.py", line 440
  File "PyLuaTblParser.py", line 440
  File "PyLuaTblParser.py", line 512
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 416
  File "PyLuaTblParser.py", line 430
  File "PyLuaTblParser.py", line 426
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 508
  File "PyLuaTblParser.py", line 440
  File "PyLuaTblParser.py", line 438
  File "PyLuaTblParser.py", line 512
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 508
  File "PyLuaTblParser.py", line 440
  File "PyLuaTblParser.py", line 436
  File "PyLuaTblParser.py", line 512
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 508
  File "PyLuaTblParser.py", line 440
  File "PyLuaTblParser.py", line 434
  File "PyLuaTblParser.py", line 512
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 424
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 426
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 546
  File "PyLuaTblParser.py", line 536
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 508
  File "PyLuaTblParser.py", line 440
  File "PyLuaTblParser.py", line 432
  File "PyLuaTblParser.py", line 512
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 424
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 426
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 508
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 424
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 512
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 424
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 508
  File "PyLuaTblParser.py", line 440
  File "PyLuaTblParser.py", line 430
  File "PyLuaTblParser.py", line 512
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 508
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 424
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 512
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 424
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 508
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 426
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 512
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 426
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 424
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 508
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 426
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 512
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 426
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 508
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 428
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 512
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 428
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 560
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 530
  File "PyLuaTblParser.py", line 520
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 546
  File "PyLuaTblParser.py", line 536
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 508
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 536
  File "PyLuaTblParser.py", line 546
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 532
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 512
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 424
  File "PyLuaTblParser.py", line 426
  File "PyLuaTblParser.py", line 428
  File "PyLuaTblParser.py", line 430
  File "PyLuaTblParser.py", line 432
  File "PyLuaTblParser.py", line 434
  File "PyLuaTblParser.py", line 436
  File "PyLuaTblParser.py", line 438
  File "PyLuaTblParser.py", line 440
  File "PyLuaTblParser.py", line 422
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 520
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 416
  File "PyLuaTblParser.py", line 440
  File "PyLuaTblParser.py", line 438
  File "PyLuaTblParser.py", line 436
  File "PyLuaTblParser.py", line 434
  File "PyLuaTblParser.py", line 418
  File "PyLuaTblParser.py", line 432
  File "PyLuaTblParser.py", line 430
  File "PyLuaTblParser.py", line 428
  File "PyLuaTblParser.py", line 426
  File "PyLuaTblParser.py", line 424
  File "PyLuaTblParser.py", line 422
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 422
  File "PyLuaTblParser.py", line 418
  File "PyLuaTblParser.py", line 424
  File "PyLuaTblParser.py", line 426
  File "PyLuaTblParser.py", line 428
  File "PyLuaTblParser.py", line 430
  File "PyLuaTblParser.py", line 432
  File "PyLuaTblParser.py", line 434
  File "PyLuaTblParser.py", line 436
  File "PyLuaTblParser.py", line 438
  File "PyLuaTblParser.py", line 440
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 416
  File "PyLuaTblParser.py", line 424
  File "PyLuaTblParser.py", line 426
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 464
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 424
  File "PyLuaTblParser.py", line 418
  File "PyLuaTblParser.py", line 426
  File "PyLuaTblParser.py", line 428
  File "PyLuaTblParser.py", line 430
  File "PyLuaTblParser.py", line 432
  File "PyLuaTblParser.py", line 434
  File "PyLuaTblParser.py", line 436
  File "PyLuaTblParser.py", line 438
  File "PyLuaTblParser.py", line 440
  File "PyLuaTblParser.py", line 422
  File "PyLuaTblParser.py", line 464
  File "PyLuaTblParser.py", line 412
  File "PyLuaTblParser.py", line 428
  File "PyLuaTblParser.py", line 430
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 570
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 548
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 422
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 548
  File "PyLuaTblParser.py", line 546
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 424
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 550
  File "PyLuaTblParser.py", line 520
  File "PyLuaTblParser.py", line 524
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 552
  File "PyLuaTblParser.py", line 560
  File "PyLuaTblParser.py", line 548
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 510
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 522
  File "PyLuaTblParser.py", line 520
  File "PyLuaTblParser.py", line 524
  File "PyLuaTblParser.py", line 540
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 520
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 534
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 510
  File "PyLuaTblParser.py", line 510
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 524
  File "PyLuaTblParser.py", line 548
  File "PyLuaTblParser.py", line 546
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 548
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 510
  File "PyLuaTblParser.py", line 522
  File "PyLuaTblParser.py", line 510
  File "PyLuaTblParser.py", line 530
  File "PyLuaTblParser.py", line 510
  File "PyLuaTblParser.py", line 546
  File "PyLuaTblParser.py", line 510
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 510
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 520
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 534
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 420
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 402
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 510
  File "PyLuaTblParser.py", line 510
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 520
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 550
  File "PyLuaTblParser.py", line 534
  File "PyLuaTblParser.py", line 520
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 520
  File "PyLuaTblParser.py", line 522
  File "PyLuaTblParser.py", line 524
  File "PyLuaTblParser.py", line 526
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 530
  File "PyLuaTblParser.py", line 532
  File "PyLuaTblParser.py", line 534
  File "PyLuaTblParser.py", line 536
  File "PyLuaTblParser.py", line 538
  File "PyLuaTblParser.py", line 540
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 544
  File "PyLuaTblParser.py", line 546
  File "PyLuaTblParser.py", line 548
  File "PyLuaTblParser.py", line 550
  File "PyLuaTblParser.py", line 552
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 560
  File "PyLuaTblParser.py", line 562
  File "PyLuaTblParser.py", line 564
  File "PyLuaTblParser.py", line 568
  File "PyLuaTblParser.py", line 570
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 456
  File "PyLuaTblParser.py", line 478
  File "PyLuaTblParser.py", line 486
  File "PyLuaTblParser.py", line 470
  File "PyLuaTblParser.py", line 456
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 456
  File "PyLuaTblParser.py", line 458
  File "PyLuaTblParser.py", line 460
  File "PyLuaTblParser.py", line 462
  File "PyLuaTblParser.py", line 464
  File "PyLuaTblParser.py", line 466
  File "PyLuaTblParser.py", line 468
  File "PyLuaTblParser.py", line 470
  File "PyLuaTblParser.py", line 472
  File "PyLuaTblParser.py", line 474
  File "PyLuaTblParser.py", line 476
  File "PyLuaTblParser.py", line 478
  File "PyLuaTblParser.py", line 480
  File "PyLuaTblParser.py", line 482
  File "PyLuaTblParser.py", line 484
  File "PyLuaTblParser.py", line 486
  File "PyLuaTblParser.py", line 488
  File "PyLuaTblParser.py", line 490
  File "PyLuaTblParser.py", line 492
  File "PyLuaTblParser.py", line 494
  File "PyLuaTblParser.py", line 496
  File "PyLuaTblParser.py", line 498
  File "PyLuaTblParser.py", line 500
  File "PyLuaTblParser.py", line 504
  File "PyLuaTblParser.py", line 506
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 526
  File "PyLuaTblParser.py", line 536
  File "PyLuaTblParser.py", line 532
  File "PyLuaTblParser.py", line 536
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 422
  File "PyLuaTblParser.py", line 424
  File "PyLuaTblParser.py", line 426
  File "PyLuaTblParser.py", line 428
  File "PyLuaTblParser.py", line 430
  File "PyLuaTblParser.py", line 432
  File "PyLuaTblParser.py", line 434
  File "PyLuaTblParser.py", line 436
  File "PyLuaTblParser.py", line 438
  File "PyLuaTblParser.py", line 440
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 550
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 524
  File "PyLuaTblParser.py", line 536
  File "PyLuaTblParser.py", line 520
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 518
  File "PyLuaTblParser.py", line 424
  File "PyLuaTblParser.py", line 578
  File "PyLuaTblParser.py", line 392
  File "PyLuaTblParser.py", line 454
  File "PyLuaTblParser.py", line 396
  File "PyLuaTblParser.py", line 398
  File "PyLuaTblParser.py", line 400
  File "PyLuaTblParser.py", line 514
  File "PyLuaTblParser.py", line 402
  File "PyLuaTblParser.py", line 410
  File "PyLuaTblParser.py", line 406
  File "PyLuaTblParser.py", line 408
  File "PyLuaTblParser.py", line 516
  File "PyLuaTblParser.py", line 412
  File "PyLuaTblParser.py", line 416
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 404
  File "PyLuaTblParser.py", line 442
  File "PyLuaTblParser.py", line 508
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 512
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 574
  File "PyLuaTblParser.py", line 444
  File "PyLuaTblParser.py", line 418
  File "PyLuaTblParser.py", line 446
  File "PyLuaTblParser.py", line 420
  File "PyLuaTblParser.py", line 450
  File "PyLuaTblParser.py", line 452
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 534
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 422
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 422
  File "PyLuaTblParser.py", line 424
  File "PyLuaTblParser.py", line 426
  File "PyLuaTblParser.py", line 428
  File "PyLuaTblParser.py", line 422
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 430
  File "PyLuaTblParser.py", line 432
  File "PyLuaTblParser.py", line 434
  File "PyLuaTblParser.py", line 436
  File "PyLuaTblParser.py", line 422
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 438
  File "PyLuaTblParser.py", line 440
  File "PyLuaTblParser.py", line 456
  File "PyLuaTblParser.py", line 458
  File "PyLuaTblParser.py", line 422
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 460
  File "PyLuaTblParser.py", line 462
  File "PyLuaTblParser.py", line 464
  File "PyLuaTblParser.py", line 466
  File "PyLuaTblParser.py", line 422
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 520
  File "PyLuaTblParser.py", line 522
  File "PyLuaTblParser.py", line 524
  File "PyLuaTblParser.py", line 526
  File "PyLuaTblParser.py", line 422
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 530
  File "PyLuaTblParser.py", line 430
  File "PyLuaTblParser.py", line 456
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 508
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 560
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 512
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 560
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 508
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 530
  File "PyLuaTblParser.py", line 520
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 512
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 530
  File "PyLuaTblParser.py", line 520
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 508
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 546
  File "PyLuaTblParser.py", line 536
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 512
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 546
  File "PyLuaTblParser.py", line 536
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 520
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 520
  File "PyLuaTblParser.py", line 568
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 546
  File "PyLuaTblParser.py", line 536
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 546
  File "PyLuaTblParser.py", line 536
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 548
  File "PyLuaTblParser.py", line 522
  File "PyLuaTblParser.py", line 538
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 524
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 520
  File "PyLuaTblParser.py", line 526
  File "PyLuaTblParser.py", line 526
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 432
  File "PyLuaTblParser.py", line 422
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 492
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 418
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 474
  File "PyLuaTblParser.py", line 520
  File "PyLuaTblParser.py", line 544
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 492
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 560
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 534
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 550
  File "PyLuaTblParser.py", line 442
  File "PyLuaTblParser.py", line 420
  File "PyLuaTblParser.py", line 420
  File "PyLuaTblParser.py", line 564
  File "PyLuaTblParser.py", line 564
  File "PyLuaTblParser.py", line 564
  File "PyLuaTblParser.py", line 418
  File "PyLuaTblParser.py", line 474
  File "PyLuaTblParser.py", line 492
  File "PyLuaTblParser.py", line 484
  File "PyLuaTblParser.py", line 482
  File "PyLuaTblParser.py", line 418
  File "PyLuaTblParser.py", line 548
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 532
  File "PyLuaTblParser.py", line 420
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 524
  File "PyLuaTblParser.py", line 548
  File "PyLuaTblParser.py", line 544
  File "PyLuaTblParser.py", line 544
  File "PyLuaTblParser.py", line 528
  File "PyLuaTblParser.py", line 546
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 448
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 420
  File "PyLuaTblParser.py", line 420
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 420
  File "PyLuaTblParser.py", line 410
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 446
  File "PyLuaTblParser.py", line 392
  File "PyLuaTblParser.py", line 416
  File "PyLuaTblParser.py", line 416
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 416
  File "PyLuaTblParser.py", line 416
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 414
  File "PyLuaTblParser.py", line 352
  File "PyLuaTblParser.py", line 346
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 344
  File "PyLuaTblParser.py", line 508
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 396
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 416
  File "PyLuaTblParser.py", line 416
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 416
  File "PyLuaTblParser.py", line 416
  File "PyLuaTblParser.py", line 450
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 410
  File "PyLuaTblParser.py", line 420
  File "PyLuaTblParser.py", line 394
  File "PyLuaTblParser.py", line 512
  File "PyLuaTblParser.py", line 390
  File "PyLuaTblParser.py", line 323
