Traceback (most recent call last):
  File "check_homework.py", line 71
  File "PyLuaTblParser.py", line 224
  File "PyLuaTblParser.py", line 724
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 706
  File "PyLuaTblParser.py", line 700
  File "PyLuaTblParser.py", line 700
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 724
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 592
  File "PyLuaTblParser.py", line 586
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 724
  File "PyLuaTblParser.py", line 724
  File "PyLuaTblParser.py", line 728
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 578
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 698
  File "PyLuaTblParser.py", line 688
  File "PyLuaTblParser.py", line 694
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 728
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 646
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 708
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 638
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 706
  File "PyLuaTblParser.py", line 698
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 644
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 706
  File "PyLuaTblParser.py", line 688
  File "PyLuaTblParser.py", line 698
  File "PyLuaTblParser.py", line 684
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 578
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 724
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 700
  File "PyLuaTblParser.py", line 674
  File "PyLuaTblParser.py", line 690
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 676
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 716
  File "PyLuaTblParser.py", line 688
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 686
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 696
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 696
  File "PyLuaTblParser.py", line 674
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 706
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 724
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 706
  File "PyLuaTblParser.py", line 706
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 720
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 716
  File "PyLuaTblParser.py", line 688
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 686
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 694
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 696
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 698
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 728
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 728
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 592
  File "PyLuaTblParser.py", line 592
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 568
  File "PyLuaTblParser.py", line 582
  File "PyLuaTblParser.py", line 578
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 582
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 646
  File "PyLuaTblParser.py", line 706
  File "PyLuaTblParser.py", line 712
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 584
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 618
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 694
  File "PyLuaTblParser.py", line 708
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 592
  File "PyLuaTblParser.py", line 588
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 724
  File "PyLuaTblParser.py", line 724
  File "PyLuaTblParser.py", line 728
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 724
  File "PyLuaTblParser.py", line 728
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 728
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 590
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 574
  File "PyLuaTblParser.py", line 570
  File "PyLuaTblParser.py", line 584
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 592
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 580
  File "PyLuaTblParser.py", line 570
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 582
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 584
  File "PyLuaTblParser.py", line 592
  File "PyLuaTblParser.py", line 578
  File "PyLuaTblParser.py", line 586
  File "PyLuaTblParser.py", line 584
  File "PyLuaTblParser.py", line 580
  File "PyLuaTblParser.py", line 584
  File "PyLuaTblParser.py", line 592
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 564
  File "PyLuaTblParser.py", line 586
  File "PyLuaTblParser.py", line 582
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 574
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 580
  File "PyLuaTblParser.py", line 570
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 582
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 584
  File "PyLuaTblParser.py", line 592
  File "PyLuaTblParser.py", line 578
  File "PyLuaTblParser.py", line 586
  File "PyLuaTblParser.py", line 584
  File "PyLuaTblParser.py", line 580
  File "PyLuaTblParser.py", line 584
  File "PyLuaTblParser.py", line 592
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 588
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 724
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 676
  File "PyLuaTblParser.py", line 700
  File "PyLuaTblParser.py", line 696
  File "PyLuaTblParser.py", line 696
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 698
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 562
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 598
  File "PyLuaTblParser.py", line 544
  File "PyLuaTblParser.py", line 568
  File "PyLuaTblParser.py", line 568
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 568
  File "PyLuaTblParser.py", line 568
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 682
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 694
  File "PyLuaTblParser.py", line 708
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 618
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 694
  File "PyLuaTblParser.py", line 708
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 674
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 676
  File "PyLuaTblParser.py", line 692
  File "PyLuaTblParser.py", line 708
  File "PyLuaTblParser.py", line 694
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 708
  File "PyLuaTblParser.py", line 686
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 662
  File "PyLuaTblParser.py", line 662
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 700
  File "PyLuaTblParser.py", line 698
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 704
  File "PyLuaTblParser.py", line 712
  File "PyLuaTblParser.py", line 700
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 708
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 548
  File "PyLuaTblParser.py", line 580
  File "PyLuaTblParser.py", line 582
  File "PyLuaTblParser.py", line 596
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 574
  File "PyLuaTblParser.py", line 718
  File "PyLuaTblParser.py", line 574
  File "PyLuaTblParser.py", line 574
  File "PyLuaTblParser.py", line 578
  File "PyLuaTblParser.py", line 578
  File "PyLuaTblParser.py", line 560
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 552
  File "PyLuaTblParser.py", line 578
  File "PyLuaTblParser.py", line 578
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 574
  File "PyLuaTblParser.py", line 718
  File "PyLuaTblParser.py", line 578
  File "PyLuaTblParser.py", line 578
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 574
  File "PyLuaTblParser.py", line 580
  File "PyLuaTblParser.py", line 582
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 548
  File "PyLuaTblParser.py", line 718
  File "PyLuaTblParser.py", line 578
  File "PyLuaTblParser.py", line 578
  File "PyLuaTblParser.py", line 596
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 722
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 706
  File "PyLuaTblParser.py", line 700
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 574
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 688
  File "PyLuaTblParser.py", line 698
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 684
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 706
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 578
  File "PyLuaTblParser.py", line 580
  File "PyLuaTblParser.py", line 582
  File "PyLuaTblParser.py", line 584
  File "PyLuaTblParser.py", line 586
  File "PyLuaTblParser.py", line 588
  File "PyLuaTblParser.py", line 590
  File "PyLuaTblParser.py", line 592
  File "PyLuaTblParser.py", line 574
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 706
  File "PyLuaTblParser.py", line 706
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 720
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 724
  File "PyLuaTblParser.py", line 698
  File "PyLuaTblParser.py", line 688
  File "PyLuaTblParser.py", line 694
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 698
  File "PyLuaTblParser.py", line 688
  File "PyLuaTblParser.py", line 694
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 728
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 548
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 568
  File "PyLuaTblParser.py", line 568
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 568
  File "PyLuaTblParser.py", line 568
  File "PyLuaTblParser.py", line 602
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 562
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 708
  File "PyLuaTblParser.py", line 702
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 676
  File "PyLuaTblParser.py", line 688
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 694
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 662
  File "PyLuaTblParser.py", line 546
  File "PyLuaTblParser.py", line 670
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 730
  File "PyLuaTblParser.py", line 544
  File "PyLuaTblParser.py", line 606
  File "PyLuaTblParser.py", line 548
  File "PyLuaTblParser.py", line 550
  File "PyLuaTblParser.py", line 552
  File "PyLuaTblParser.py", line 666
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 562
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 560
  File "PyLuaTblParser.py", line 668
  File "PyLuaTblParser.py", line 564
  File "PyLuaTblParser.py", line 568
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 724
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 594
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 728
  File "PyLuaTblParser.py", line 726
  File "PyLuaTblParser.py", line 596
  File "PyLuaTblParser.py", line 570
  File "PyLuaTblParser.py", line 598
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 602
  File "PyLuaTblParser.py", line 604
  File "PyLuaTblParser.py", line 662
  File "PyLuaTblParser.py", line 546
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 676
  File "PyLuaTblParser.py", line 700
  File "PyLuaTblParser.py", line 696
  File "PyLuaTblParser.py", line 702
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 676
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 724
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 578
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 580
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 582
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 584
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 586
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 588
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 728
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 708
  File "PyLuaTblParser.py", line 702
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 676
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 686
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 718
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 574
  File "PyLuaTblParser.py", line 718
  File "PyLuaTblParser.py", line 574
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 578
  File "PyLuaTblParser.py", line 580
  File "PyLuaTblParser.py", line 574
  File "PyLuaTblParser.py", line 718
  File "PyLuaTblParser.py", line 582
  File "PyLuaTblParser.py", line 584
  File "PyLuaTblParser.py", line 586
  File "PyLuaTblParser.py", line 588
  File "PyLuaTblParser.py", line 574
  File "PyLuaTblParser.py", line 718
  File "PyLuaTblParser.py", line 590
  File "PyLuaTblParser.py", line 592
  File "PyLuaTblParser.py", line 608
  File "PyLuaTblParser.py", line 610
  File "PyLuaTblParser.py", line 574
  File "PyLuaTblParser.py", line 718
  File "PyLuaTblParser.py", line 612
  File "PyLuaTblParser.py", line 614
  File "PyLuaTblParser.py", line 616
  File "PyLuaTblParser.py", line 618
  File "PyLuaTblParser.py", line 574
  File "PyLuaTblParser.py", line 718
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 674
  File "PyLuaTblParser.py", line 676
  File "PyLuaTblParser.py", line 678
  File "PyLuaTblParser.py", line 574
  File "PyLuaTblParser.py", line 718
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 682
  File "PyLuaTblParser.py", line 582
  File "PyLuaTblParser.py", line 608
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 676
  File "PyLuaTblParser.py", line 700
  File "PyLuaTblParser.py", line 698
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 706
  File "PyLuaTblParser.py", line 700
  File "PyLuaTblParser.py", line 694
  File "PyLuaTblParser.py", line 708
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 662
  File "PyLuaTblParser.py", line 718
  File "PyLuaTblParser.py", line 574
  File "PyLuaTblParser.py", line 590
  File "PyLuaTblParser.py", line 662
  File "PyLuaTblParser.py", line 718
  File "PyLuaTblParser.py", line 574
  File "PyLuaTblParser.py", line 676
  File "PyLuaTblParser.py", line 662
  File "PyLuaTblParser.py", line 698
  File "PyLuaTblParser.py", line 662
  File "PyLuaTblParser.py", line 706
  File "PyLuaTblParser.py", line 662
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 662
  File "PyLuaTblParser.py", line 662
  File "PyLuaTblParser.py", line 662
  File "PyLuaTblParser.py", line 546
  File "PyLuaTblParser.py", line 662
  File "PyLuaTblParser.py", line 718
  File "PyLuaTblParser.py", line 574
  File "PyLuaTblParser.py", line 590
  File "PyLuaTblParser.py", line 662
  File "PyLuaTblParser.py", line 718
  File "PyLuaTblParser.py", line 574
  File "PyLuaTblParser.py", line 676
  File "PyLuaTblParser.py", line 662
  File "PyLuaTblParser.py", line 698
  File "PyLuaTblParser.py", line 662
  File "PyLuaTblParser.py", line 706
  File "PyLuaTblParser.py", line 662
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 670
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 730
  File "PyLuaTblParser.py", line 544
  File "PyLuaTblParser.py", line 606
  File "PyLuaTblParser.py", line 548
  File "PyLuaTblParser.py", line 550
  File "PyLuaTblParser.py", line 552
  File "PyLuaTblParser.py", line 666
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 562
  File "PyLuaTblParser.py", line 558
  File "PyLuaTblParser.py", line 560
  File "PyLuaTblParser.py", line 668
  File "PyLuaTblParser.py", line 564
  File "PyLuaTblParser.py", line 568
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 724
  File "PyLuaTblParser.py", line 728
  File "PyLuaTblParser.py", line 726
  File "PyLuaTblParser.py", line 596
  File "PyLuaTblParser.py", line 594
  File "PyLuaTblParser.py", line 662
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 570
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 598
  File "PyLuaTblParser.py", line 602
  File "PyLuaTblParser.py", line 604
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 608
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 692
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 720
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 676
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 698
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 674
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 698
  File "PyLuaTblParser.py", line 720
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 708
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 706
  File "PyLuaTblParser.py", line 688
  File "PyLuaTblParser.py", line 698
  File "PyLuaTblParser.py", line 684
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 708
  File "PyLuaTblParser.py", line 694
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 708
  File "PyLuaTblParser.py", line 686
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 554
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 662
  File "PyLuaTblParser.py", line 662
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 706
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 694
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 568
  File "PyLuaTblParser.py", line 592
  File "PyLuaTblParser.py", line 590
  File "PyLuaTblParser.py", line 588
  File "PyLuaTblParser.py", line 586
  File "PyLuaTblParser.py", line 570
  File "PyLuaTblParser.py", line 584
  File "PyLuaTblParser.py", line 582
  File "PyLuaTblParser.py", line 580
  File "PyLuaTblParser.py", line 578
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 678
  File "PyLuaTblParser.py", line 688
  File "PyLuaTblParser.py", line 684
  File "PyLuaTblParser.py", line 688
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 574
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 578
  File "PyLuaTblParser.py", line 580
  File "PyLuaTblParser.py", line 582
  File "PyLuaTblParser.py", line 584
  File "PyLuaTblParser.py", line 586
  File "PyLuaTblParser.py", line 588
  File "PyLuaTblParser.py", line 590
  File "PyLuaTblParser.py", line 592
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 616
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 570
  File "PyLuaTblParser.py", line 578
  File "PyLuaTblParser.py", line 580
  File "PyLuaTblParser.py", line 582
  File "PyLuaTblParser.py", line 584
  File "PyLuaTblParser.py", line 586
  File "PyLuaTblParser.py", line 588
  File "PyLuaTblParser.py", line 590
  File "PyLuaTblParser.py", line 592
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 564
  File "PyLuaTblParser.py", line 580
  File "PyLuaTblParser.py", line 582
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 704
  File "PyLuaTblParser.py", line 712
  File "PyLuaTblParser.py", line 700
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 662
  File "PyLuaTblParser.py", line 546
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 700
  File "PyLuaTblParser.py", line 674
  File "PyLuaTblParser.py", line 690
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 676
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 724
  File "PyLuaTblParser.py", line 728
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 678
  File "PyLuaTblParser.py", line 678
  File "PyLuaTblParser.py", line 706
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 708
  File "PyLuaTblParser.py", line 708
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 584
  File "PyLuaTblParser.py", line 574
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 644
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 570
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 626
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 696
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 708
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 644
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 706
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 694
  File "PyLuaTblParser.py", line 702
  File "PyLuaTblParser.py", line 686
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 674
  File "PyLuaTblParser.py", line 676
  File "PyLuaTblParser.py", line 678
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 682
  File "PyLuaTblParser.py", line 684
  File "PyLuaTblParser.py", line 686
  File "PyLuaTblParser.py", line 688
  File "PyLuaTblParser.py", line 690
  File "PyLuaTblParser.py", line 692
  File "PyLuaTblParser.py", line 694
  File "PyLuaTblParser.py", line 696
  File "PyLuaTblParser.py", line 698
  File "PyLuaTblParser.py", line 700
  File "PyLuaTblParser.py", line 702
  File "PyLuaTblParser.py", line 704
  File "PyLuaTblParser.py", line 706
  File "PyLuaTblParser.py", line 708
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 712
  File "PyLuaTblParser.py", line 714
  File "PyLuaTblParser.py", line 716
  File "PyLuaTblParser.py", line 720
  File "PyLuaTblParser.py", line 722
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 706
  File "PyLuaTblParser.py", line 712
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 646
  File "PyLuaTblParser.py", line 706
  File "PyLuaTblParser.py", line 712
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 694
  File "PyLuaTblParser.py", line 712
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 718
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 724
  File "PyLuaTblParser.py", line 662
  File "PyLuaTblParser.py", line 546
  File "PyLuaTblParser.py", line 700
  File "PyLuaTblParser.py", line 674
  File "PyLuaTblParser.py", line 690
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 676
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 716
  File "PyLuaTblParser.py", line 688
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 686
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 696
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 696
  File "PyLuaTblParser.py", line 674
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 706
  File "PyLuaTblParser.py", line 662
  File "PyLuaTblParser.py", line 546
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 724
  File "PyLuaTblParser.py", line 662
  File "PyLuaTblParser.py", line 546
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 706
  File "PyLuaTblParser.py", line 706
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 720
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 716
  File "PyLuaTblParser.py", line 688
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 686
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 694
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 696
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 698
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 662
  File "PyLuaTblParser.py", line 546
  File "PyLuaTblParser.py", line 728
  File "PyLuaTblParser.py", line 728
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 570
  File "PyLuaTblParser.py", line 578
  File "PyLuaTblParser.py", line 580
  File "PyLuaTblParser.py", line 582
  File "PyLuaTblParser.py", line 584
  File "PyLuaTblParser.py", line 586
  File "PyLuaTblParser.py", line 588
  File "PyLuaTblParser.py", line 590
  File "PyLuaTblParser.py", line 592
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 568
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 580
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 712
  File "PyLuaTblParser.py", line 706
  File "PyLuaTblParser.py", line 694
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 686
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 710
  File "PyLuaTblParser.py", line 702
  File "PyLuaTblParser.py", line 594
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 716
  File "PyLuaTblParser.py", line 716
  File "PyLuaTblParser.py", line 716
  File "PyLuaTblParser.py", line 570
  File "PyLuaTblParser.py", line 626
  File "PyLuaTblParser.py", line 644
  File "PyLuaTblParser.py", line 636
  File "PyLuaTblParser.py", line 634
  File "PyLuaTblParser.py", line 570
  File "PyLuaTblParser.py", line 700
  File "PyLuaTblParser.py", line 706
  File "PyLuaTblParser.py", line 684
  File "PyLuaTblParser.py", line 572
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 566
  File "PyLuaTblParser.py", line 660
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 708
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 702
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 672
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 676
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 680
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 678
  File "PyLuaTblParser.py", line 542
  File "PyLuaTblParser.py", line 556
  File "PyLuaTblParser.py", line 664
  File "PyLuaTblParser.py", line 600
  File "PyLuaTblParser.py", line 724
  File "PyLuaTblParser.py", line 576
  File "PyLuaTblParser.py", line 477
